version: '3.9'

services:
  postgres:
    container_name: good-game_db
    restart: always
    image: postgres:15.3-alpine
    env_file: "./packages/server/.env"
    ports: 
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    environment: 
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  server:
    container_name: good-game_server
    image: good-game_server
    build:
      context: .
      dockerfile: Dockerfile.server      
    restart: always
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    env_file: "./packages/server/.env"
    environment:
      SERVER_PORT: ${SERVER_PORT}



