name: Push to GitHub Container Registry

on:
  push:
    branches:
      - main
      - feature/tgg-65

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: set lower case owner name
        run: |
          echo "OWNER_LC=${OWNER,,}" >>${GITHUB_ENV}
        env:
          OWNER: '${{ github.repository_owner }}'
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push server image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.server
          push: true
          tags: ghcr.io/${{ env.OWNER_LC }}/${{ github.event.repository.name }}/server:${{ github.sha }}
      
      - name: Execute commands on Yandex Cloud Virtual Machine
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: 51.250.51.19
          username: goodgame
          password: goodgame
          script: |
            CONTAINER=$(sudo docker ps -a -q --filter="name=prakticum-server") 
            echo "Container with server: $CONTAINER"
            IMAGE=$(sudo docker images -q ghcr.io/${{env.OWNER_LC}}/${{github.event.repository.name}}/server)
            echo "Image with server: $IMAGE"
            
            echo "Pull new server image from Github Container Registry" 
            for n in {1..5}; do sudo docker pull ghcr.io/${{env.OWNER_LC}}/${{github.event.repository.name}}/server:${{github.sha}} && break; done
            
            echo "Remove docker container with previous version of server"
            if [ ! "$CONTAINER" ]; then sudo docker stop $CONTAINER && sudo docker rm $CONTAINER; fi
            if [ ! "$IMAGE" ]; then sudo docker rmi $IMAGE; fi
            
            echo "Run new container"
            sudo docker run -d -p 3001:3001 --name prakticum-server ghcr.io/${{ env.OWNER_LC }}/${{ github.event.repository.name }}/server:${{ github.sha }}
            
            echo "Show images"
            sudo docker image ls
            echo "Show container"
            sudo docker ps -a
